In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append('../kaggle_prediction_library/') 
import preprocess
import feature_engineering
import submission
from sklearn.model_selection import train_test_split

# from hyperopt import tpe, fmin, Trials
# import hyperopt.hp as hp

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import log_loss
from sklearn.feature_selection import chi2
from sklearn.metrics import r2_score
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import brier_score_loss

### Read data

In [3]:
# For now we can use this, but we may need to recreate this once the teams have been announced
# The new version should only include feasible tourney matchups to make life easier
sub_df = pd.read_csv('SampleSubmission2024.csv', index_col=False)

In [4]:
regular_season_results = pd.read_csv('../data/MRegularSeasonDetailedResults.csv')
detailed_tourney_results = pd.read_csv('../data/MNCAATourneyDetailedResults.csv')
rankings = pd.read_csv('../data/MMasseyOrdinals.csv')
seeds = pd.read_csv('../data/MNCAATourneySeeds.csv')

# kp_rankings = pd.read_csv('../data/kenpom_pre_tourney_snapshot.csv')

regular_season_results_w = pd.read_csv('../data/WRegularSeasonDetailedResults.csv')
detailed_tourney_results_w = pd.read_csv('../data/WNCAATourneyDetailedResults.csv')

mteams = pd.read_csv('../data/MTeams.csv')
wteams = pd.read_csv('../data/WTeams.csv')

seeds_w = pd.read_csv('../data/WNCAATourneySeeds.csv')

# M538 = pd.read_csv('../data/M538.csv')
# W538 = pd.read_csv('../data/W538.csv')

seed_round = pd.read_csv("../data/MNCAATourneySeedRoundSlots.csv")
seeds = pd.read_csv("../data/MNCAATourneySeeds.csv")

first_round_odds_data = pd.read_csv('../data/first_round_odds_2024.csv')

In [5]:
# #This is temporary, will remove once we are predicting 2024 instead of 2023
# detailed_tourney_results = detailed_tourney_results[detailed_tourney_results.Season < 2023].copy()
# detailed_tourney_results_w = detailed_tourney_results_w[detailed_tourney_results_w.Season < 2023].copy()

### Set Up Data

In [6]:
to_predict_mens, to_predict_womens, regular_season_games, regular_season_games_w = preprocess.full_setup(detailed_tourney_results, regular_season_results,
               detailed_tourney_results_w, regular_season_results_w,
               sub_df, mteams)

/Users/skylerdale/workspace/kaggle-ncaam/2024_model/production_notebooks/../kaggle_prediction_library/submission.py:45: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([mens_historical_games, womens_historical_games, sub], axis = 0)

In [7]:
sub_df[ (sub_df.Team1 == 1194)
       & (sub_df.Team2 == 1321)]

                 ID  Pred Season  Team1  Team2
420  2024_1194_1321   0.5   2024   1194   1321

### Add Features

In [8]:
to_predict_womens = feature_engineering.TournamentSeed(tourney_seeds=seeds_w).add(to_predict_womens)
to_predict_womens = feature_engineering.Efficiency(games=regular_season_games_w, away_bonus=0).add(to_predict_womens)
to_predict_womens = feature_engineering.RoundNumber(seeds, seed_round).add(to_predict_womens)
to_predict_womens = feature_engineering.TeamNames(wteams).add(to_predict_womens)


# to_predict_womens = feature_engineering.FiveThirtyEight(fivethirtyeight_df=W538).add(to_predict_womens)

/Users/skylerdale/workspace/kaggle-ncaam/2024_model/production_notebooks/../kaggle_prediction_library/feature_engineering.py:132: FutureWarning: The provided callable <function mean at 0x107a180d0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  final = all_games3.groupby(['Season', 'Team1']).agg(adj_oe=('adj_oe', np.mean), adj_de=('adj_de', np.mean)).reset_index()

In [9]:
#to_predict_womens.to_csv("../development_notebooks/to_predict_women.csv")
to_predict_womens.to_csv("to_predict_women.csv")

In [10]:
to_predict_mens = feature_engineering.TeamNames(mteams).add(to_predict_mens)
to_predict_mens = feature_engineering.FirstRoundOdds(first_round_odds_data).add(to_predict_mens)

In [11]:
to_predict_mens = feature_engineering.RoundNumber(seeds, seed_round).add(to_predict_mens)

In [12]:
to_predict_mens = feature_engineering.SeasonStats(regular_season_games).add(to_predict_mens)
# to_predict_mens = feature_engineering.FiveThirtyEight(fivethirtyeight_df=M538).add(to_predict_mens)
to_predict_mens = feature_engineering.PreSeasonAPRankings(rankings_df=rankings).add(to_predict_mens)
to_predict_mens = feature_engineering.TournamentSeed(tourney_seeds=seeds).add(to_predict_mens)
to_predict_mens = feature_engineering.Efficiency(games=regular_season_games, away_bonus=0).add(to_predict_mens)
to_predict_mens = feature_engineering.FinalRanking(rankings_df=rankings, system='WLK').add(to_predict_mens) # switched in 2024 because SAG dissapeared
# to_predict_mens = feature_engineering.Kenpom(kp_snapshot=kp_rankings).add(to_predict_mens)
# this one takes 3 minutes to run
# to_predict_mens = feature_engineering.TeamQuality(games=regular_season_games).add(to_predict_mens)

/Users/skylerdale/workspace/kaggle-ncaam/2024_model/production_notebooks/../kaggle_prediction_library/feature_engineering.py:222: FutureWarning: The provided callable <function mean at 0x107a180d0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  season_statistics = df.groupby(["Season", 'Team1'])[boxscore_cols].agg(np.mean).reset_index()
/Users/skylerdale/workspace/kaggle-ncaam/2024_model/production_notebooks/../kaggle_prediction_library/feature_engineering.py:132: FutureWarning: The provided callable <function mean at 0x107a180d0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  final = all_games3.groupby(['Season', 'Team1']).agg(adj_oe=('adj_oe', np.mean), adj_de=('adj_de', np.mean)).reset_index()
/Users/skylerdale/workspace/kaggle-ncaam/2024_model/production_notebooks/../kaggle_prediction_library/feature_engineering.py:157: FutureWarning: The provided callable <function mean at 0x107a180d0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  end_rankings = end_rankings.groupby(['TeamID', 'Season']).agg({'OrdinalRank':np.mean})

### Split Dataset

In [13]:
first_round_df = to_predict_mens[to_predict_mens.GameRound == 1].copy()
other_rounds_df = to_predict_mens[to_predict_mens.GameRound > 1].copy()

In [14]:
# first_round_df.to_csv("to_predict_mens_first_round.csv")
# other_rounds_df.to_csv("to_predict_mens_other_rounds.csv")
to_predict_mens.to_csv("to_predict_mens.csv")

In [15]:
to_predict_mens

,type,ID,Pred,Season,Team1,Team2,Outcome,Gender,margin,t1_TeamName,...,t2_Seed,seed_diff,t1_adj_oe,t1_adj_de,t1_adj_margin,t2_adj_oe,t2_adj_de,t2_adj_margin,t1_final_rank,t2_final_rank
0,Historical,2003_1421_1411,NaN,2003,1421,1411,1,M,8,UNC Asheville,...,16,0,104.526528,119.437414,-14.910886,106.509926,111.907479,-5.397553,67.338190,67.151721
1,Historical,2003_1112_1436,NaN,2003,1112,1436,1,M,29,Arizona,...,16,-15,119.071254,93.286794,25.784460,106.884988,101.850357,5.034632,95.514642,72.897644
2,Historical,2003_1113_1272,NaN,2003,1113,1272,1,M,13,Arizona St,...,7,3,121.219248,101.541410,19.677837,114.009765,96.248862,17.760903,84.233153,86.681285
3,Historical,2003_1141_1166,NaN,2003,1141,1166,1,M,6,C Michigan,...,6,5,113.038016,105.370558,7.667458,117.078846,97.251061,19.827785,84.559424,87.153435
4,Historical,2003_1143_1301,NaN,2003,1143,1301,1,M,2,California,...,9,-1,111.121076,101.087582,10.033494,116.019889,102.254106,13.765783,84.394558,81.876843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4641,Prediction,2024_1436_1443,0.5,2024,1436,1443,None,M,None,Vermont,...,15,-2,111.763491,103.053463,8.710028,109.468610,105.358921,4.109689,77.511765,73.474664
4642,Prediction,2024_1255_1436,0.5,2024,1255,1436,None,M,None,Longwood,...,13,3,106.002723,106.490960,-0.488237,111.763491,103.053463,8.710028,71.295401,77.511765
4643,Prediction,2024_1324_1443,0.5,2024,1324,1443,None,M,None,Oakland,...,15,-1,112.623027,105.763750,6.859277,109.468610,105.358921,4.109689,75.283916,73.474664
4644,Prediction,2024_1255_1324,0.5,2024,1255,1324,None,M,None,Longwood,...,14,2,106.002723,106.490960,-0.488237,112.623027,105.763750,6.859277,71.295401,75.283916
4645,Prediction,2024_1255_1443,0.5,2024,1255,1443,None,M,None,Longwood,...,15,1,106.002723,106.490960,-0.488237,109.468610,105.358921,4.109689,71.295401,73.474664