In [134]:
import pandas as pd
import numpy as np
import sys
sys.path.append('../kaggle_prediction_library/') 
import preprocess
import feature_engineering
import submission
import validation
from sklearn.model_selection import train_test_split

# from hyperopt import tpe, fmin, Trials
# import hyperopt.hp as hp

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import log_loss
from sklearn.feature_selection import chi2
from sklearn.metrics import r2_score
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import brier_score_loss
from sklearn.pipeline import make_pipeline

In [135]:
to_predict_mens = pd.read_csv("to_predict_mens.csv")

In [136]:
to_predict_mens[(to_predict_mens["GameRound"] == 1) & (to_predict_mens["Season"] == 2024)][["t1_TeamName", "t2_TeamName", "final_odds"]].head()

       t1_TeamName  t2_TeamName  final_odds
2644   Connecticut      Stetson       -26.5
2705       Iowa St  S Dakota St       -16.5
2765      Illinois  Morehead St       -12.5
2824        Auburn         Yale       -13.0
2882  San Diego St          UAB        -6.0

In [137]:
pd.set_option('display.max_columns', None)
1345
to_predict_mens[(to_predict_mens["Season"] == 2024)][["Team1", "t1_TeamName", "t1_adj_margin"]].drop_duplicates().sort_values(by="t1_adj_margin")

      Team1   t1_TeamName  t1_adj_margin
2738   1212     Grambling     -11.277963
2722   1224        Howard      -8.255369
3001   1391       Stetson      -6.125959
2934   1255      Longwood      -0.488237
3032   1389    St Peter's       0.528788
...     ...           ...            ...
2695   1235       Iowa St      28.618729
3006   1388  St Mary's CA      28.632492
2632   1120        Auburn      28.847706
2630   1163   Connecticut      29.752956
2739   1222       Houston      33.038480

[63 rows x 3 columns]

In [138]:
to_predict_mens[(to_predict_mens["GameRound"] == 1) & (to_predict_mens["Season"] == 2024)
                & (to_predict_mens["Team2"] == 1345)]

,Unnamed: 0,type,ID,Pred,Season,Team1,Team2,Outcome,Gender,margin,t1_TeamName,t1_FirstD1Season,t1_LastD1Season,t2_TeamName,t2_FirstD1Season,t2_LastD1Season,final_odds,GameRound,t1_FGM,t1_FGA,t1_FGM3,t1_FGA3,t1_OR,t1_Ast,t1_TO,t1_Stl,t1_PF,t1_FTA,t1_FTM,t1_PointDiff,t2_FGM,t2_FGA,t2_FGM3,t2_FGA3,t2_OR,t2_Ast,t2_TO,t2_Stl,t2_PF,t2_FTA,t2_FTM,t2_PointDiff,t1_OrdinalRank,t2_OrdinalRank,t1_Seed,t2_Seed,seed_diff,t1_adj_oe,t1_adj_de,t1_adj_margin,t2_adj_oe,t2_adj_de,t2_adj_margin,t1_final_rank,t2_final_rank
4164,4164,Prediction,2024_1212_1345,0.5,2024,1212,1345,NaN,M,NaN,Grambling,1985,2024,Purdue,1985,2024,25.5,1,22.580645,52.354839,5.322581,15.612903,7.741935,9.16129,12.741935,7.129032,16.16129,20.741935,14.645161,-3.741935,28.515152,58.393939,8.333333,20.424242,11.030303,18.393939,10.969697,5.666667,14.363636,25.0,18.030303,13.242424,25.0,2.0,16,1,15,101.155352,112.433315,-11.277963,127.87684,100.690725,27.186115,65.379039,97.181957

### Prepare data

In [139]:
def prepare_data(to_predict_mens, season):

    to_predict_mens_first_round_train = to_predict_mens[(to_predict_mens["GameRound"] == 1)
                                                        & (to_predict_mens.final_odds.notnull())
                                                        & (to_predict_mens.Season < season)
                                                        ].copy()
    
    to_predict_mens_train = to_predict_mens[(to_predict_mens.Season < season)].copy()

    to_predict_mens_first_round_test = to_predict_mens[(to_predict_mens.Season == season)
                                                    & (to_predict_mens.GameRound == 1)
                                                    & (to_predict_mens.final_odds.notnull())
                                                    ].copy()

    to_predict_mens_other_rounds_test = to_predict_mens[(to_predict_mens.Season == season)
                                                    & (to_predict_mens.GameRound > 1)
                                                    ].copy()
    
    return to_predict_mens_first_round_train, to_predict_mens_train, to_predict_mens_first_round_test, to_predict_mens_other_rounds_test

### Odds Model Training

In [140]:
def train_odds_model(to_predict_mens_first_round_train):

    best_params = {"C": .1}
    model = LogisticRegression(**best_params)
    pipeline = make_pipeline(StandardScaler(), model)
    odds_model = pipeline.fit(to_predict_mens_first_round_train[["final_odds"]], to_predict_mens_first_round_train["Outcome"])
    
    return odds_model

### Statistics Model Training

In [141]:
def train_statistics_model(to_predict_mens_train, statistics_features):

    best_params = {"C": .1}
    model = LogisticRegression(**best_params)
    pipeline = make_pipeline(StandardScaler(), model)
    statistics_model = pipeline.fit(to_predict_mens_train[statistics_features], to_predict_mens_train["Outcome"])

    return statistics_model

### Inference

In [142]:
def inference(to_predict_mens_first_round_test, to_predict_mens_other_rounds_test, odds_model, statistics_model, features):

    pred_proba = odds_model.predict_proba(to_predict_mens_first_round_test[["final_odds"]].copy())[:,1]
    to_predict_mens_first_round_test["odds_pred"] = pred_proba

    pred_proba = statistics_model.predict_proba(to_predict_mens_first_round_test[features].copy())[:,1]
    to_predict_mens_first_round_test["statistics_pred"] = pred_proba

    to_predict_mens_first_round_test["Pred"] = (to_predict_mens_first_round_test.odds_pred * .75) + \
                                                (to_predict_mens_first_round_test.statistics_pred * .25)
    

   

    pred_proba = statistics_model.predict_proba(to_predict_mens_other_rounds_test[features].copy())[:,1]
    to_predict_mens_other_rounds_test["Pred"] = pred_proba

    mens_sub_tmp = pd.concat([to_predict_mens_first_round_test,
            to_predict_mens_other_rounds_test], axis=0)
    
    mens_sub = mens_sub_tmp[["ID", "Pred"]]
    
    return mens_sub, mens_sub_tmp

### Full Pipeline

In [143]:
def run(to_predict_mens, season, statistics_features):
    
    # get data
    to_predict_mens_first_round_train, to_predict_mens_train, to_predict_mens_first_round_test, to_predict_mens_other_rounds_test= prepare_data(to_predict_mens, season)
    
    # train
    odds_model = train_odds_model(to_predict_mens_first_round_train)
    statistics_model = train_statistics_model(to_predict_mens_train, statistics_features)

    # inference
    mens_sub, mens_sub_tmp = inference(to_predict_mens_first_round_test, to_predict_mens_other_rounds_test, odds_model, statistics_model, statistics_features) 

    return mens_sub, mens_sub_tmp

In [144]:
statistics_features = ['t1_adj_margin', 't2_adj_margin', 't1_final_rank', 't2_final_rank', 't1_OrdinalRank', 't2_OrdinalRank']
mens_sub, mens_sub_tmp = run(to_predict_mens, 2024, statistics_features)

In [145]:
mens_sub_tmp

,Unnamed: 0,type,ID,Pred,Season,Team1,Team2,Outcome,Gender,margin,t1_TeamName,t1_FirstD1Season,t1_LastD1Season,t2_TeamName,t2_FirstD1Season,t2_LastD1Season,final_odds,GameRound,t1_FGM,t1_FGA,t1_FGM3,t1_FGA3,t1_OR,t1_Ast,t1_TO,t1_Stl,t1_PF,t1_FTA,t1_FTM,t1_PointDiff,t2_FGM,t2_FGA,t2_FGM3,t2_FGA3,t2_OR,t2_Ast,t2_TO,t2_Stl,t2_PF,t2_FTA,t2_FTM,t2_PointDiff,t1_OrdinalRank,t2_OrdinalRank,t1_Seed,t2_Seed,seed_diff,t1_adj_oe,t1_adj_de,t1_adj_margin,t2_adj_oe,t2_adj_de,t2_adj_margin,t1_final_rank,t2_final_rank,odds_pred,statistics_pred
2644,2644,Prediction,2024_1163_1391,0.973791,2024,1163,1391,NaN,M,NaN,Connecticut,1985,2024,Stetson,1985,2024,-26.5,1,29.088235,58.647059,8.794118,23.970588,10.088235,18.529412,9.117647,6.235294,16.235294,19.529412,14.500000,17.058824,26.032258,56.838710,8.677419,23.774194,7.645161,12.677419,10.064516,4.903226,15.193548,18.000000,13.741935,-0.645161,5.0,25.0,1,16,-15,129.274967,99.522011,29.752956,111.776325,117.902284,-6.125959,94.318459,70.554232,0.973850,0.973617
2705,2705,Prediction,2024_1235_1355,0.904221,2024,1235,1355,NaN,M,NaN,Iowa St,1985,2024,S Dakota St,2006,2024,-16.5,1,27.147059,58.588235,6.529412,18.735294,9.235294,15.735294,10.205882,10.441176,16.470588,21.147059,14.735294,14.264706,27.387097,57.064516,8.322581,22.967742,6.806452,12.709677,10.935484,5.935484,14.838710,17.354839,12.419355,3.870968,25.0,25.0,2,15,-13,118.434176,89.815447,28.618729,112.197479,106.651629,5.545849,89.194748,71.844042,0.904857,0.902312
2765,2765,Prediction,2024_1228_1287,0.842534,2024,1228,1287,NaN,M,NaN,Illinois,1985,2024,Morehead St,1985,2024,-12.5,1,29.294118,62.176471,8.323529,23.823529,11.382353,13.000000,10.294118,4.235294,15.352941,23.500000,17.500000,10.617647,25.633333,55.233333,8.800000,24.933333,8.600000,13.433333,11.366667,5.633333,16.700000,17.300000,12.366667,6.766667,23.0,25.0,3,14,-11,126.695216,103.281219,23.413996,116.322100,104.771613,11.550487,89.953873,75.127965,0.846368,0.831032
2824,2824,Prediction,2024_1120_1463,0.855514,2024,1120,1463,NaN,M,NaN,Auburn,1985,2024,Yale,1985,2024,-13.0,1,28.911765,60.823529,8.029412,22.794118,9.794118,17.911765,10.147059,7.411765,19.205882,23.235294,17.470588,15.294118,27.482759,59.517241,7.275862,21.034483,8.241379,14.655172,8.931034,5.793103,15.413793,16.000000,11.310345,5.413793,25.0,25.0,4,13,-9,123.071547,94.223841,28.847706,113.087044,103.963759,9.123286,91.943632,78.691305,0.855035,0.856951
2882,2882,Prediction,2024_1361_1412,0.720304,2024,1361,1412,NaN,M,NaN,San Diego St,1985,2024,UAB,1985,2024,-6.0,1,25.656250,58.437500,6.906250,22.093750,9.750000,13.031250,10.281250,7.250000,17.718750,21.906250,15.968750,6.843750,26.696970,59.393939,6.151515,18.606061,11.212121,13.242424,11.303030,6.515152,16.151515,24.030303,17.848485,1.575758,25.0,25.0,5,12,-7,116.668849,97.730092,18.938757,116.680459,111.080019,5.600440,86.912819,75.519870,0.694056,0.799047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4641,4641,Prediction,2024_1436_1443,0.618597,2024,1436,1443,NaN,M,NaN,Vermont,1985,2024,WKU,1985,2024,NaN,4,25.093750,56.468750,8.343750,24.906250,6.593750,13.062500,8.468750,5.718750,13.968750,16.781250,12.125000,6.812500,28.900000,62.033333,6.600000,19.200000,8.466667,12.866667,13.333333,7.700000,18.666667,20.433333,14.700000,4.833333,25.0,25.0,13,15,-2,111.763491,103.053463,8.710028,109.468610,105.358921,4.109689,77.511765,73.474664,NaN,NaN
4642,4642,Prediction,2024_1255_1436,0.302089,2024,1255,1436,NaN,M,NaN,Longwood,2005,2024,Vermont,1985,2024,NaN,3,26.096774,58.580645,5.677419,16.580645,11.838710,12.516129,11.967742,6.935484,18.677419,23.129032,15.903226,4.096774,25.093750,56.468750,8.343750,24.906250,6.593750,13.062500,8.468750,5.718750,13.968750,16.781250,12.125000,6.812500,25.0,25.0,16,13,3,106.002723,106.490960,-0.488237,111.763491,103.053463,8.710028,71.295401,77.511765,NaN,NaN
4643,4643,Prediction,2024_1324_1443,0.561411,2024,1324,1443,NaN,M,NaN,Oakland,2000,2024,WKU,1985,2024,NaN,3,26.911765,59.852941,8.558824,24.411765,9.264706,14.352941,10.852941,6.705882,15.088235,18.500000,14.029412,3.500000,28.900000,62.033333,6.600000,19.200000,8.466667,12.866667,13.333333,7.700000,18.666667,20.433333,14.700000,4.833333,25.0,25.0,14,15,-1,112.623027,105.763750,6.859277,109.468610,105.358921,4.109689,75.283916,73.474664,NaN,NaN
4644,4644,Prediction,2024_1255_1324,0.354191,2024,1255,1324,NaN,M,NaN,Longwood,2005,2024,Oakland,2000,2024,NaN,4,26.096774,58.580645,5.677419,16.580645,11.838710,12.516129,11.967742,6.935484,18.677419,23.129032,15.903226,4.096774,26.911765,59.852941,8.558824,24.411765,9.264706,14.352941,10.852941,6.705882,15.088235,18.500000,14.029412,3.500000,25.0,25.0,16,14,2,106.002723,106.490960,-0.488237,112.623027,105.763750,6.859277,71.295401,75.283916,NaN,NaN
4645,4645,Prediction,2024_1255_1443,0.412467,2024,1255,1443,NaN,M,NaN,Longwood,2005,2024,WKU,1985,2024,NaN,4,26.096774,58.580645,5.677419,16.580645,11.838710,12.516129,11.967742,6.935484,18.677419,23.129032,15.903226,4.096774,28.900000,62.033333,6.600000,19.200000,8.466667,12.866667,13.333333,7.700000,18.666667,20.433333,14.700000,4.833333,25.0,25.0,16,15,1,106.002723,106.490960,-0.488237,109.468610,105.358921,4.109689,71.295401,73.474664,NaN,NaN

### Womens

In [146]:
to_predict_women = pd.read_csv("to_predict_women.csv")

to_predict_women_train = to_predict_women[to_predict_women.Season != 2024] 
to_predict_women_test = to_predict_women[to_predict_women.Season == 2024]

In [147]:
statistics_features = ['seed_diff', 't1_adj_margin', 't2_adj_margin']
best_params = {"C": .1}
model = LogisticRegression(**best_params)
pipeline = make_pipeline(StandardScaler(), model)
statistics_model = pipeline.fit(to_predict_women_train[statistics_features], to_predict_women_train["Outcome"])

In [148]:
pred_proba = statistics_model.predict_proba(to_predict_women_test[statistics_features].copy())[:,1]
to_predict_women_test["Pred"] = pred_proba
womens_sub = to_predict_women_test[["ID", "Pred"]]

/var/folders/h5/f91pbgmj0rj6v0ls3y8zc5l40000gn/T/ipykernel_73463/593629811.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_predict_women_test["Pred"] = pred_proba

In [149]:
final_sub = pd.concat([mens_sub, womens_sub], axis=0)

In [150]:
final_sub.to_csv("traditional_format_sub.csv")

### Sanity Check

In [151]:
mens_sub_tmp.columns

Index(['Unnamed: 0', 'type', 'ID', 'Pred', 'Season', 'Team1', 'Team2',
       'Outcome', 'Gender', 'margin', 't1_TeamName', 't1_FirstD1Season',
       't1_LastD1Season', 't2_TeamName', 't2_FirstD1Season', 't2_LastD1Season',
       'final_odds', 'GameRound', 't1_FGM', 't1_FGA', 't1_FGM3', 't1_FGA3',
       't1_OR', 't1_Ast', 't1_TO', 't1_Stl', 't1_PF', 't1_FTA', 't1_FTM',
       't1_PointDiff', 't2_FGM', 't2_FGA', 't2_FGM3', 't2_FGA3', 't2_OR',
       't2_Ast', 't2_TO', 't2_Stl', 't2_PF', 't2_FTA', 't2_FTM',
       't2_PointDiff', 't1_OrdinalRank', 't2_OrdinalRank', 't1_Seed',
       't2_Seed', 'seed_diff', 't1_adj_oe', 't1_adj_de', 't1_adj_margin',
       't2_adj_oe', 't2_adj_de', 't2_adj_margin', 't1_final_rank',
       't2_final_rank', 'odds_pred', 'statistics_pred'],
      dtype='object')

In [163]:
mens_sub_tmp.Season.unique()

array([2024])

In [ ]:
statistics_features = ['t1_adj_margin', 't1_final_rank', 't1_OrdinalRank']

mens_sub_tmp[(mens_sub_tmp.Team1 == 1163)][statistics_features].drop_duplicates()

,t1_adj_margin,t2_adj_margin,t1_final_rank,t2_final_rank,t1_OrdinalRank,t2_OrdinalRank
2644,29.752956,-6.125959,94.318459,70.554232,5.0,25.0
2630,29.752956,28.618729,94.318459,89.194748,5.0,25.0
2631,29.752956,23.413996,94.318459,89.953873,5.0,23.0
2633,29.752956,18.938757,94.318459,86.912819,5.0,25.0
2635,29.752956,14.572821,94.318459,84.394558,5.0,25.0
2636,29.752956,20.038251,94.318459,84.900415,5.0,10.0
2637,29.752956,16.314393,94.318459,83.046109,5.0,25.0
2638,29.752956,15.243467,94.318459,82.124635,5.0,25.0
2639,29.752956,8.911419,94.318459,76.573516,5.0,25.0
2640,29.752956,5.600440,94.318459,75.519870,5.0,25.0
2641,29.752956,9.123286,94.318459,78.691305,5.0,25.0
2642,29.752956,11.550487,94.318459,75.127965,5.0,25.0
2643,29.752956,5.545849,94.318459,71.844042,5.0,25.0
2645,29.752956,24.661760,94.318459,90.847465,5.0,20.0
2649,29.752956,28.632492,94.318459,84.233153,5.0,25.0
2651,29.752956,19.693724,94.318459,85.831250,5.0,25.0
2652,29.752956,17.185992,94.318459,86.033588,5.0,25.0
2653,29.752956,22.130603,94.318459,87.939874,5.0,18.0
2654,29.752956,19.493905,94.318459,83.185685,5.0,25.0
2655,29.752956,18.355434,94.318459,85.077029,5.0,25.0
2656,29.752956,15.155424,94.318459,80.940804,5.0,25.0
2659,29.752956,2.112178,94.318459,72.331433,5.0,25.0
2660,29.752956,-8.255369,94.318459,64.480952,5.0,25.0
2661,29.752956,27.186115,94.318459,97.181957,5.0,2.0
2662,29.752956,27.364284,94.318459,92.605689,5.0,7.0
2663,29.752956,23.615220,94.318459,89.560373,5.0,8.0
2664,29.752956,20.626138,94.318459,88.531436,5.0,1.0
2665,29.752956,24.211835,94.318459,86.242330,5.0,11.0
2666,29.752956,15.179941,94.318459,82.908696,5.0,25.0
2667,29.752956,18.463969,94.318459,83.327530,5.0,19.0
2668,29.752956,15.743113,94.318459,84.559424,5.0,25.0
2669,29.752956,15.121827,94.318459,85.634834,5.0,25.0
2671,29.752956,13.110432,94.318459,81.053487,5.0,25.0
2672,29.752956,14.806881,94.318459,80.609279,5.0,25.0
2673,29.752956,9.648463,94.318459,80.829232,5.0,25.0
2675,29.752956,0.528788,94.318459,68.790175,5.0,25.0
2676,29.752956,-11.277963,94.318459,65.379039,5.0,25.0
2677,29.752956,33.038480,94.318459,95.514642,5.0,6.0
2678,29.752956,21.901352,94.318459,88.852862,5.0,4.0
2679,29.752956,20.683957,94.318459,88.227827,5.0,17.0
2680,29.752956,26.636213,94.318459,90.380569,5.0,9.0
2681,29.752956,20.598718,94.318459,86.458023,5.0,25.0
2682,29.752956,18.184265,94.318459,84.075015,5.0,25.0
2683,29.752956,18.292304,94.318459,85.443909,5.0,25.0
2684,29.752956,12.399170,94.318459,83.919965,5.0,25.0
2685,29.752956,15.755136,94.318459,80.393360,5.0,13.0
2687,29.752956,11.287927,94.318459,79.366411,5.0,25.0
2688,29.752956,15.013969,94.318459,81.167319,5.0,24.0
2689,29.752956,8.710028,94.318459,77.511765,5.0,25.0
2690,29.752956,6.859277,94.318459,75.283916,5.0,25.0
2691,29.752956,4.109689,94.318459,73.474664,5.0,25.0
2692,29.752956,-0.488237,94.318459,71.295401,5.0,25.0

In [153]:
detailed_tourney_results = pd.read_csv('../../2025_model/data/MNCAATourneyDetailedResults.csv')

In [154]:
results_2024 = detailed_tourney_results[detailed_tourney_results.Season == 2024]

In [155]:
results_2024["ID"] = np.where(results_2024["WTeamID"] < results_2024["LTeamID"],
                              results_2024["Season"].astype(str) + "_" + results_2024["WTeamID"].astype(str) + "_" + results_2024["LTeamID"].astype(str),
                              results_2024["Season"].astype(str) + "_" + results_2024["LTeamID"].astype(str) + "_" + results_2024["WTeamID"].astype(str))

results_2024["Outcome"] = np.where(results_2024["WTeamID"] < results_2024["LTeamID"],
                             1, 0)

/var/folders/h5/f91pbgmj0rj6v0ls3y8zc5l40000gn/T/ipykernel_73463/1777742413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_2024["ID"] = np.where(results_2024["WTeamID"] < results_2024["LTeamID"],
/var/folders/h5/f91pbgmj0rj6v0ls3y8zc5l40000gn/T/ipykernel_73463/1777742413.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_2024["Outcome"] = np.where(results_2024["WTeamID"] < results_2024["LTeamID"],

In [156]:
tmp = mens_sub_tmp.merge(results_2024, how="inner", on = "ID")

In [157]:
brier_score_loss(tmp["Outcome_y"], tmp["Pred"])

0.19180412002846867

In [158]:
tmp2 = tmp[["ID","Team1", "Team2", "Pred", 't1_TeamName', 't2_TeamName']]
tmp2[tmp2.t1_TeamName == "Connecticut"]

                ID  Team1  Team2      Pred  t1_TeamName   t2_TeamName
0   2024_1163_1391   1163   1391  0.973791  Connecticut       Stetson
30  2024_1163_1228   1163   1228  0.715230  Connecticut      Illinois
31  2024_1163_1361   1163   1361  0.796906  Connecticut  San Diego St
32  2024_1163_1321   1163   1321  0.852221  Connecticut  Northwestern
34  2024_1163_1345   1163   1345  0.464124  Connecticut        Purdue